# Generated by Django 3.2 on 2022-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuestracking', '0004_auto_20220221_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('CREA', 'Créateur'), ('CONT', 'Contributeur')], default='CONT', max_length=128),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('PM', 'Project manager'), ('PS', 'Project staff')], default='PS', max_length=128),
        ),
    ]
