# Generated by Django 3.2 on 2022-02-21 15:21

from django.db import migrations
from ..models import Contributor


def correct_permissions_and_role(apps, schema_editor):
    contributors = Contributor.objects.all()
    for contributor in contributors:
        contributor.role = 'PM' if contributor.permission == 'CREA' else 'PS'
        contributor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issuestracking', '0005_auto_20220221_1618'),
    ]

    operations = [
        migrations.RunPython(correct_permissions_and_role),
    ]
