# Generated by Django 4.0.2 on 2022-02-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuestracking', '0008_alter_comment_author_alter_comment_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_user',
        ),
    ]
